# Aqua registry configuration for zvelte-check
# Submit this to https://github.com/aquaproj/aqua-registry
# Place in pkgs/ampcode/zvelte-check/registry.yaml

packages:
  - type: github_release
    repo_owner: ampcode
    repo_name: zvelte-check
    description: Fast Svelte diagnostic tool written in Zig
    asset: zvelte-check-{{.OS}}-{{.Arch}}.tar.gz
    format: tar.gz
    files:
      - name: zvelte-check
    replacements:
      darwin: darwin
      linux: linux
      amd64: x86_64
      arm64: aarch64
    overrides:
      - goos: windows
        asset: zvelte-check-{{.OS}}-{{.Arch}}.zip
        format: zip
        files:
          - name: zvelte-check
            src: zvelte-check.exe
    supported_envs:
      - darwin/amd64
      - darwin/arm64
      - linux/amd64
      - linux/arm64
      - windows/amd64
    checksum:
      type: github_release
      asset: checksums.txt
      algorithm: sha256
