// SvelteKit virtual module type stubs
// Auto-generated by zvelte-check

declare module "$app/environment" {
  export const browser: boolean;
  export const dev: boolean;
  export const building: boolean;
  export const version: string;
}

declare module "$app/stores" {
  import type { Readable } from "svelte/store";
  export const page: Readable<{
    url: URL;
    params: Record<string, string>;
    route: { id: string | null };
    status: number;
    error: Error | null;
    data: Record<string, any>;
    state: Record<string, any>;
    form: any;
  }>;
  export const navigating: Readable<{
    from: { url: URL; params: Record<string, string>; route: { id: string | null } } | null;
    to: { url: URL; params: Record<string, string>; route: { id: string | null } } | null;
    type: 'load' | 'unload' | 'link' | 'goto' | 'popstate';
    willUnload: boolean;
    delta?: number;
    complete: Promise<void>;
  } | null>;
  export const updated: Readable<boolean> & { check: () => Promise<boolean> };
}

declare module "$app/navigation" {
  export function goto(url: string | URL, opts?: {
    replaceState?: boolean;
    noScroll?: boolean;
    keepFocus?: boolean;
    invalidateAll?: boolean;
    state?: any;
  }): Promise<void>;
  export function invalidate(url: string | URL | ((url: URL) => boolean)): Promise<void>;
  export function invalidateAll(): Promise<void>;
  export function preloadData(url: string | URL): Promise<Record<string, any>>;
  export function preloadCode(...urls: string[]): Promise<void>;
  export function beforeNavigate(callback: (navigation: {
    from: { url: URL; params: Record<string, string>; route: { id: string | null } } | null;
    to: { url: URL; params: Record<string, string>; route: { id: string | null } } | null;
    willUnload: boolean;
    type: 'load' | 'unload' | 'link' | 'goto' | 'popstate';
    cancel: () => void;
  }) => void): void;
  export function afterNavigate(callback: (navigation: {
    from: { url: URL; params: Record<string, string>; route: { id: string | null } } | null;
    to: { url: URL; params: Record<string, string>; route: { id: string | null } } | null;
    type: 'load' | 'unload' | 'link' | 'goto' | 'popstate';
    willUnload: boolean;
  }) => void): void;
  export function onNavigate(callback: (navigation: {
    from: { url: URL; params: Record<string, string>; route: { id: string | null } } | null;
    to: { url: URL; params: Record<string, string>; route: { id: string | null } };
    type: 'link' | 'goto' | 'popstate';
  }) => void | (() => void) | Promise<void | (() => void)>): void;
  export function disableScrollHandling(): void;
  export function pushState(url: string | URL, state: any): void;
  export function replaceState(url: string | URL, state: any): void;
}

declare module "$app/forms" {
  export function enhance<Success = Record<string, any>, Failure = Record<string, any>>(
    form: HTMLFormElement,
    options?: {
      formElement?: HTMLFormElement;
      formData?: FormData;
      action?: URL;
      submitter?: HTMLElement | null;
      cancel?: () => void;
      controller?: AbortController;
    } | ((input: { formElement: HTMLFormElement; formData: FormData; action: URL; submitter: HTMLElement | null; cancel: () => void; controller: AbortController }) => Promise<void | ((opts: { formElement: HTMLFormElement; formData: FormData; action: URL; result: { type: 'success' | 'failure' | 'redirect' | 'error'; status?: number; data?: Success | Failure; location?: string; error?: any }; update: (options?: { reset?: boolean; invalidateAll?: boolean }) => Promise<void>; }) => Promise<void>)>)
  ): { destroy: () => void };
  export function applyAction<T = Record<string, any>>(result: { type: 'success' | 'failure' | 'redirect' | 'error'; status?: number; data?: T; location?: string; error?: any }): Promise<void>;
}

declare module "$app/paths" {
  export const base: string;
  export const assets: string;
  export function resolveRoute(id: string, params: Record<string, string | undefined>): string;
}

declare module "$app/state" {
  export const page: {
    readonly url: URL;
    readonly params: Record<string, string>;
    readonly route: { readonly id: string | null };
    readonly status: number;
    readonly error: Error | null;
    readonly data: Record<string, any>;
    readonly state: Record<string, any>;
    readonly form: any;
  };
  export const navigating: {
    readonly from: { readonly url: URL; readonly params: Record<string, string>; readonly route: { readonly id: string | null } } | null;
    readonly to: { readonly url: URL; readonly params: Record<string, string>; readonly route: { readonly id: string | null } } | null;
    readonly type: 'load' | 'unload' | 'link' | 'goto' | 'popstate';
    readonly willUnload: boolean;
    readonly delta?: number;
    readonly complete: Promise<void>;
  } | null;
  export const updated: {
    readonly current: boolean;
    check: () => Promise<boolean>;
  };
}

declare module "$app/server" {
  export function read(asset: string): Response;
}

// Generic .svelte file type declaration
// Allows tsgo to resolve imports like `import Component from './Button.svelte'`
// Named exports from .svelte files are typed via their generated .svelte.ts files
declare module "*.svelte" {
  import { SvelteComponent } from "svelte";
  const component: typeof SvelteComponent<any, any, any>;
  export default component;
}

// unplugin-icons virtual module stubs
// Allows tsgo to resolve imports like `import Icon from '~icons/lucide/check'`
declare module "~icons/*" {
  import { SvelteComponent } from "svelte";
  const component: typeof SvelteComponent;
  export default component;
}

declare module "$app/types" {
  // Re-export common SvelteKit types
  export type Navigation = {
    from: { url: URL; params: Record<string, string>; route: { id: string | null } } | null;
    to: { url: URL; params: Record<string, string>; route: { id: string | null } } | null;
    type: 'load' | 'unload' | 'link' | 'goto' | 'popstate';
    willUnload: boolean;
    delta?: number;
    complete: Promise<void>;
  };
  export type Page<Data = Record<string, any>> = {
    url: URL;
    params: Record<string, string>;
    route: { id: string | null };
    status: number;
    error: Error | null;
    data: Data;
    state: Record<string, any>;
    form: any;
  };
}

// SvelteKit $env/* virtual module types
declare module "$env/static/private" {
  const env: Record<string, string>;
  export = env;
}

declare module "$env/static/public" {
  const env: Record<string, string>;
  export = env;
}

declare module "$env/dynamic/private" {
  export const env: Record<string, string | undefined>;
}

declare module "$env/dynamic/public" {
  export const env: Record<string, string | undefined>;
}

// Vite import.meta.env ambient types
interface ImportMetaEnv {
  readonly MODE: string;
  readonly BASE_URL: string;
  readonly PROD: boolean;
  readonly DEV: boolean;
  readonly SSR: boolean;
  [key: string]: any;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

// Note: SvelteKit ./$types resolution relies on the generated
// .svelte-kit/types/*/$types.d.ts files. Users should run `pnpm dev`
// or `pnpm build` once to generate these types.

// SvelteKit App namespace for locals and platform
declare namespace App {
  interface Locals {}
  interface Platform {}
  interface PageState {}
}
