#!/bin/bash
# Dump svelte2tsx output for a Svelte file.
#
# Usage: ./scripts/dump-svelte2tsx.sh <file.svelte>
#
# Requires: svelte2tsx installed in test-fixtures/comparison/
# Install with: cd test-fixtures/comparison && pnpm add -D svelte2tsx

set -e

if [ -z "$1" ]; then
    echo "Usage: $0 <file.svelte>"
    echo ""
    echo "Dumps the TypeScript that svelte2tsx generates."
    echo "Compare with 'zig build dump -- <file>' to find transformer bugs."
    exit 1
fi

FILE="$1"

if [ ! -f "$FILE" ]; then
    echo "Error: File not found: $FILE"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
COMPARISON_DIR="$PROJECT_ROOT/test-fixtures/comparison"

# Check if svelte2tsx is installed
if [ ! -d "$COMPARISON_DIR/node_modules/svelte2tsx" ]; then
    echo "Error: svelte2tsx not installed."
    echo "Run: cd $COMPARISON_DIR && pnpm add -D svelte2tsx"
    exit 1
fi

# Get absolute path to file
ABS_FILE="$(cd "$(dirname "$FILE")" && pwd)/$(basename "$FILE")"

cd "$COMPARISON_DIR"
node --input-type=module << EOF
import { svelte2tsx } from 'svelte2tsx';
import { readFileSync } from 'fs';

const source = readFileSync('$ABS_FILE', 'utf-8');
const result = svelte2tsx(source, {
    filename: '$(basename "$FILE")',
    isTsFile: true,
    mode: 'ts',
    version: 5
});

console.log('// Generated by svelte2tsx');
console.log('// File: $FILE');
console.log('');
console.log(result.code);
EOF
